BARRIER_TEST_OBJS = \
		   barrier1.o \
		   barrier2.o \
		   barrier3.o \
		   barrier4.o \
		   barrier5.o

BENCH_TEST_OBJS = \
		  benchlib.o \
		  benchtest1.o \
		  benchtest2.o \
		  benchtest3.o \
		  benchtest4.o \
		  benchtest5.o 

CANCEL_TEST_OBJS = \
		   cancel1.o \
		   cancel2.o \
		   cancel3.o \
		   cancel4.o \
		   cancel5.o \
		   cancel6a.o \
		   cancel6d.o

CLEANUP_TEST_OBJS = \
		    cleanup0.o \
		    cleanup1.o \
		    cleanup2.o \
		    cleanup3.o

CONDVAR_TEST_OBJS = \
		    condvar1.o \
		    condvar2_1.o \
		    condvar2.o \
		    condvar3_1.o \
		    condvar3_2.o \
		    condvar3_3.o \
		    condvar3.o \
		    condvar5.o \
		    condvar6.o \
		    condvar8.o \
		    #condvar9.o  \
		    #condvar1_1.o \
		    condvar1_2.o \
		    condvar4.o \
		    condvar5.o \
		    condvar7.o \

COUNT_TEST_OBJS = \
		  count1.o

CREATE_TEST_OBJS = \
		   create1.o \
		   create2.o \
		   create3.o

DELAY_TEST_OBJS = \
		  delay1.o \
		  delay2.o

DETACH_TEST_OBJS = \
		   detach1.o

EQUAL_TEST_OBJS = \
		  equal1.o

ERRNO_TEST_OBJS = \
		  errno1.o

EXCEPTION_TEST_OBJS = \
		      exception1.o \
		      exception2.o \
		      exception3.o

EXIT_TEST_OBJS = \
		 exit1.o \
		 exit2.o \
		 exit3.o \
		 exit4.o \
		 exit5.o

INHERIT_TEST_OBJS = \
		    inherit1.o

JOIN_TEST_OBJS = \
		 join0.o \
		 join1.o \
		 join2.o \
		 join3.o \
		 join4.o 

KILL_TEST_OBJS = \
		 kill1.o

MUTEX_TEST_OBJS = \
		  mutex1.o \
		  mutex1e.o \
		  mutex1n.o \
		  mutex1r.o \
		  mutex2.o \
		  mutex2e.o \
		  mutex2r.o \
		  mutex3.o \
		  mutex3e.o \
		  mutex3r.o \
		  mutex4.o \
		  mutex5.o \
		  mutex6.o \
		  mutex6e.o \
		  mutex6es.o \
		  mutex6n.o \
		  mutex6r.o \
		  mutex6rs.o \
		  mutex6s.o \
		  mutex7.o \
		  mutex7e.o \
		  mutex7n.o \
		  mutex7r.o \
		  mutex8.o \
		  mutex8e.o \
		  mutex8n.o \
		  mutex8r.o

ONCE_TEST_OBJS = \
		 once1.o \
		 once2.o \
		 once3.o \
		 once4.o

PRIORITY_TEST_OBJS = \
		     priority1.o \
		     priority2.o

REUSE_TEST_OBJS = \
		  reuse1.o \
		  reuse2.o

RWLOCK_TEST_OBJS = \
		   rwlock1.o \
		   rwlock2.o \
		   rwlock2_t.o \
		   rwlock3.o \
		   rwlock3_t.o \
		   rwlock4.o \
		   rwlock4_t.o \
		   rwlock5.o \
		   rwlock5_t.o \
		   rwlock6.o \
		   rwlock6_t2.o \
		   rwlock6_t.o \
		   rwlock7.o \
		   rwlock8.o 

SELF_TEST_OBJS = \
		 self1.o \
		 self2.o

SEM_TEST_OBJS = \
		semaphore1.o \
		semaphore2.o \
		semaphore3.o \
		semaphore4.o \
		semaphore4t.o \
		semaphore5.o \
		semaphore6.o

SPIN_TEST_OBJS = \
		 spin1.o \
		 spin2.o \
		 spin3.o \
		 spin4.o

STRESS_TEST_OBJS = \
		   #stress1.o

TSD_TEST_OBJS = \
		tsd1.o \
		tsd2.o

VALID_TEST_OBJS = \
		  valid1.o \
		  valid2.o

TEST_OBJS = test_main.o


OBJS = $(BARRIER_TEST_OBJS)  $(CONDVAR_TEST_OBJS) $(COUNT_TEST_OBJS) \
     $(CREATE_TEST_OBJS) $(DELAY_TEST_OBJS) $(DETACH_TEST_OBJS) $(EQUAL_TEST_OBJS) $(ERRNO_TEST_OBJS)  \
     $(EXIT_TEST_OBJS) $(JOIN_TEST_OBJS) $(KILL_TEST_OBJS) $(KILL_TEST_OBJS) $(MUTEX_TEST_OBJS) $(ONCE_TEST_OBJS) \
     $(SELF_TEST_OBJS) $(SEM_TEST_OBJS) $(SPIN_TEST_OBJS) $(STRESS_TEST_OBJS) \
     $(TEST_OBJS)
#$(EXCEPTION_TEST_OBJS)
#$(BENCH_TEST_OBJS)
obj-y += $(OBJS)
